workspace:
  base: /workdir
  path: rchain-perf-harness


services:
  bootstrap:
    image: rchain/rnode:dev
    detach: true
    commands:
      - /opt/docker/bin/rnode -c ./drone/config/bootstrap.toml run

  validator1:
    image: rchain/rnode:dev
    detach: true
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator1.toml run

pipeline:
  deploy:
    image: rchain/rnode:dev
    commands:
      - sleep 15
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 deploy --from "0x1" --phlo-limit 0 --phlo-price 0 --nonce 0 drone/config/contracts/performance/loop_recursive.rho

  propose:
    image: rchain/rnode:dev
    commands:
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 -c propose
