workspace:
  base: /workdir
  path: rchain-perf-harness


services:
  bootstrap:
    image: rchain/rnode:dev
    detach: true
    commands:
      - /opt/docker/bin/rnode -c ./drone/config/bootstrap.toml run

  validator1:
    image: rchain/rnode:dev
    detach: true
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator1.toml run

pipeline:
  deploy:
    image: rchain/rnode:dev
    commands:
      - sleep 20
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 deploy --from "0x1" --phlo-limit 0 --phlo-price 0 --nonce 0 drone/config/contracts/performance/loop_recursive.rho

  propose:
    image: rchain/rnode:dev
    commands:
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 propose

  push-metrics:
    image: byrnedo/alpine-curl
    commands:
      - metrics=`curl bootstrap:39992`
      - echo $metrics | curl --data-binary @- http://prometheus-pushgateway:9091/metrics/job/${DRONE_COMMIT_SHA}/instance/bootstrap
