workspace:
  base: /workdir
  path: rchain-perf-harness

services:
  bootstrap:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    pull: true
    detach: true
    environment:
      - JAVA_OPTS=-Dkamon.metric.tick-interval=5s
    commands:
      - echo "RNode image version: $RNODE_IMAGE_VERSION"
      - /opt/docker/bin/rnode -c ./drone/config/bootstrap.toml run

  validator1:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    pull: true
    detach: true
    environment:
      - JAVA_OPTS=-Dkamon.metric.tick-interval=5s
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator1.toml run

  validator2:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    pull: true
    detach: true
    environment:
      - JAVA_OPTS=-Dkamon.metric.tick-interval=5s
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator2.toml run

  validator3:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    pull: true
    detach: true
    environment:
      - JAVA_OPTS=-Dkamon.metric.tick-interval=5s
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator3.toml run

  validator4:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    pull: true
    detach: true
    environment:
      - JAVA_OPTS=-Dkamon.metric.tick-interval=5s
    commands:
      - sleep 10
      - /opt/docker/bin/rnode -c ./drone/config/validator4.toml run

  push-metrics:
    image: cfmanteiga/alpine-bash-curl-jq
    detach: true
    commands:
      - cd metrics
      - sleep 15
      - /bin/bash loop-metrics.sh

pipeline:
  deploy:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    commands:
      - sleep 40
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 deploy --from "0x1" --phlo-limit 0 --phlo-price 0 --nonce 0 drone/config/contracts/tut-philosophers.rho

  propose:
    image: rchain/rnode:${RNODE_IMAGE_VERSION=dev}
    commands:
      - /opt/docker/bin/rnode --grpc-host validator1 --grpc-port 30015 propose

  gatling:
    image: hseeberger/scala-sbt
    commands:
      - pwd
      - cd templater
      - sbt -Drnodes.0=bootstrap:30015 -Drnodes.1=validator1:30015 -Drnodes.2=validator2:30015 -Drnodes.3=validator3:30015 -Drnodes.4=validator4:30015 runner/gatling:test | tee sbt.out
      - sleep 20
      - echo "stop" > ../metrics/stop-loop
      - /bin/bash ../etc/check-build-status.sh
    when:
      event: push

  gatling-custom-contract:
    image: hseeberger/scala-sbt
    commands:
      - pwd
      - cd templater
      - sbt -Dcontract=$CONTRACT -Drnodes.0=bootstrap:30015 -Drnodes.1=validator1:30015 -Drnodes.2=validator2:30015 -Drnodes.3=validator3:30015 -Drnodes.4=validator4:30015 runner/gatling:test | tee sbt.out
      - sleep 20
      - echo "stop" > ../metrics/stop-loop
      - /bin/bash ../etc/check-build-status.sh
    when:
      event: deployment
      environment: custom-contract

  push-metrics-delete-metrics:
    image: cfmanteiga/alpine-bash-curl-jq
    commands:
      - for instance in bootstrap validator1 validator2 validator3 validator4; do curl -XDELETE http://prometheus-pushgateway:9091/metrics/job/${DRONE_COMMIT_SHA}/instance/$instance; done
    when:
      status: [ success, failure ]
