workspace:
  base: /workdir
  path: rchain-perf-harness

pipeline:

  start-bootstrap:
    image: rchain/rnode:master
    detach: true
    commands:
      - bin/rnode -c ./config/bootstrap.toml run

  deploy:
    image: rchain/rnode:master
    commands:
      - -c ./config/bootstrap.toml deploy --from "0x1" --phlo-limit 0 --phlo-price 0 --nonce 0 drone/config/contracts/performance/loop_recursive.rho

  propose:
    image: rchain/rnode:master
    commands:
      - -c ./config/bootstrap.toml propose
