[server]
host = "localhost"
port = 30021
metrics-port = 30022
no-upnp = true
default-timeout = 1000
map-size = 200000000
data-dir = "./data"
bootstrap = "rnode://7119ad2a26cdcde63dca675c4f2a4df85f404726@localhost:30011"

[grpc-server]
host = "grpc"
port = 30025